// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZJCbshBLlWp40gFYcOgEPf356oKX2PQ',
    appId: '1:400558672817:web:f152505776e4668fdfcb90',
    messagingSenderId: '400558672817',
    projectId: 'parking-poc-39dbb',
    authDomain: 'parking-poc-39dbb.firebaseapp.com',
    storageBucket: 'parking-poc-39dbb.firebasestorage.app',
    measurementId: 'G-70T1RJVETH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3LmUlfBcJhaX3V1DDT42HgCzmDRbKzak',
    appId: '1:400558672817:android:82a43e75f69acf16dfcb90',
    messagingSenderId: '400558672817',
    projectId: 'parking-poc-39dbb',
    storageBucket: 'parking-poc-39dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnS9EOSuT_nLzXc5EZjIhXp1SCIWSamMs',
    appId: '1:400558672817:ios:29de6616f7c8b6c9dfcb90',
    messagingSenderId: '400558672817',
    projectId: 'parking-poc-39dbb',
    storageBucket: 'parking-poc-39dbb.firebasestorage.app',
    iosBundleId: 'com.parking.app',
  );
}
