name: app
description: "ParKing - Peer-to-peer parking marketplace POC"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  image_picker: ^1.0.5
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  fake_cloud_firestore: ^2.4.0

flutter:
  uses-material-design: true
