name: app
description: "ParKing - Peer-to-peer parking marketplace POC"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  image_picker: ^1.0.5
  image: ^4.1.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.6
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  fake_cloud_firestore: ^3.1.0

flutter:
  uses-material-design: true
